### ISSUE TITLE
Will there be an SDK for .NET MAUI and if so, when?

### ISSUE THREAD

**Issue by hot33331** [adobe/xamarin-acpanalytics#21]
### Expected Behaviour
There is an SDK for .NET MAUI

### Actual Behaviour
I do not know if and when there is/will be an SDK for .NET MAUI

Will there be an SDK for .NET MAUI and if so, when?

**Comment by caseymcj** [comment]
Hi Tobias, at the moment we don't have any plans to release an SDK for .NET MAUI. If this changes, we'll let you know.

Casey

**Comment by alexanderdibenedetto** [comment]
Hi all - I wanted to bring to your attention that I have created (and welcome contributions to) a .NET MAUI iOS library for this: https://github.com/alexanderdibenedetto/aepsdk-core-net-ios based upon https://github.com/adobe/aepsdk-core-ios.

I am going to create one for the https://github.com/adobe/aepsdk-analytics-ios also.

I'm going to try to mirror Adobe's repositories one to one. I'll create a core iOS, analytics iOS, core Android, and analytics Android and then ship them to nuget.org. If anyone would like to assist please let me know.
