### ISSUE TITLE
.NET MAUI Support

### ISSUE THREAD

**Issue by alexanderdibenedetto** [adobe/xamarin-acpanalytics#22]
### Expected Behavior
Since Xamarin Forms is going away and being replaced with .NET MAUI, will there be an effort to update these to the latest iOS/Android native SDKs and target .NET MAUI?

https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin

Do you allow contributions from the .NET MAUI community to make this happen if you aren't planning to take this on? 

### Actual Behaviour
Only Xamarin Forms supported.

**Comment by ahmyr** [comment]
@alexanderdibenedetto, we do not have any plans to add .NET MAUI support at this time. We do gladly take community contributions.

**Comment by ahmyr** [comment]
Going to close this. You can keep watch on SDK platform support here:
https://developer.adobe.com/client-sdks/documentation/current-sdk-versions/

**Comment by alexanderdibenedetto** [comment]
@ahmyr just wanted to let you know my plans; any support Adobe can provide would be great. I haven't yet but could choose to publish these to nuget.org, but if Adobe would be willing to do that I'd appreciate it. I'm also willing to move these repositories over to you and just make regular contributions if and as needed. Let me know what level of interaction with the open source community y'all are willing to make here.

Hi all - I wanted to bring to your attention that I have created (and welcome contributions to) a .NET MAUI iOS library for this: https://github.com/alexanderdibenedetto/aepsdk-core-net-ios based upon https://github.com/adobe/aepsdk-core-ios.

I am going to create one for the https://github.com/adobe/aepsdk-analytics-ios also.

I'm going to try to mirror Adobe's repositories one to one. I'll create a core iOS, analytics iOS, core Android, and analytics Android and then ship them to nuget.org. If anyone would like to assist please let me know.
