### ISSUE TITLE
Xamarin Support for Latest iOS and Android Native Analytics SDK

### ISSUE THREAD

**Issue by ngpp564** [adobe/xamarin-acpanalytics#24]
We are trying to integrate Adobe Analytics SDK to our Xamarin Forms application and we are looking for iOS and Android native bindings for latest native packages
Android v2.0.2 : https://github.com/adobe/aepsdk-analytics-android/releases/tag/v2.0.2
iOS v4.0.0 : https://github.com/adobe/aepsdk-analytics-ios/releases/tag/4.0.0

Can we get some information on when this is planned to be released.

**Comment by cdhoffmann** [comment]
Hey @ngpp564, thank you for submitting this ticket. Unfortunately, we have no plans to support Xamarin with our latest native extensions. If this changes, we will be sure to reach out.
